### ISSUE TITLE
Syncing doesn't work

### ISSUE THREAD

**Issue by polm** [maxpower47/PinDroid#83]
As mentioned in #59 and elsewhere syncing with Pinboard doesn't work.

When I tried checking my Pinboard account via the app, it said the last sync date was some time in September, which matches up with the timeline of #59. 

Any idea what might cause this? If not, is there any way to dump the bookmarks on my phone to json or something? If I could just get at the data I can manually migrate it to the web...

**Comment by polm** [comment]
Uninstalling and reinstalling fixed it, though I lost all un-synced bookmarks naturally. 

It'd be great if there were a way to dump the local bookmarks to json or something to handle situations like this.

**Comment by edgaron** [comment]
I also encountered this problem.  I tracked backwards to the last item that was synced.  The next item was missing a description - didn't even have the "[No title]" default.  I edited the entry adding a description, and tried to sync again.  It worked.

**Comment by polm** [comment]
@edgaron Thanks, that worked for me too.

**Comment by frankdeath** [comment]
PinDroid (v3.3.2) failed to sync for me for the last 9 months.  A few of my bookmarks were missing descriptions, but adding descriptions didn't the solve problem.

I looked at the ``adb logcat`` output and saw this bookmark error:
```
10-16 12:51:31.134 19170 19208 D BookmarkSyncAdapter: Beginning Manual Download Sync
10-16 12:51:31.198 19170 19208 D BookmarkContentProvider Query: content://com.pindroid.providers.BookmarkContentProvider/bookmark
10-16 12:51:31.457 19170 19208 D apiCallUrl: https://api.pinboard.in/v1/posts/add?auth_token=[REDACTED]
10-16 12:51:32.001 19170 19208 D BookmarkSyncAdapter: Error editing bookmark: b6f28e27a657ae6ecd4f365ee57434e7
```

I copied the PinboardBookmarks.db from this location on my phone to my computer (root access required):
```
/data/data/com.pindroid/databases/PinboardBookmarks.db
```

I was then able to open the sqlite database with [sqlitebrowser](http://sqlitebrowser.org) and I found that the bookmark with hash ``b6f28e27a657ae6ecd4f365ee57434e7`` had a synced value of ``-1`` (see screenshot):

![sqlitebrowser-pinboardbookmarks](https://user-images.githubusercontent.com/1928514/47060952-21ab3200-d195-11e8-8370-7fa0df8d720c.png)

I deleted the two bookmarks with synced values of ``-1``.  I also deleted the four bookmarks in the screenshot that had empty meta hashes and synced values of ``1``.

I used ``adb push`` to install the edited database (root access required).  I restarted the app and initiated a manual sync, which was successful (but it took a long time since it needed to sync thousands of bookmarks).

It should be possible to modify the app to correct these database problems automatically so that people without root access can fix their syncing problems.  Unfortunately I'm not familiar enough with the source code to do that.

**Comment by catwell** [comment]
I had a similar issue which I fixed today by editing the title of the first incorrectly synced bookmark to remove a special character.

**Comment by mfasold** [comment]
I also had the same issue: the bookmarks of the last two months had not been synced. :( Nothing seemed wrong with the first not-synced bookmarks. I used `adb logcat` which pointed towards several bookmarks with wrongly parsed descriptions (very long ones, containing HTML / CSS code). First I hoped to access the application database as above, but this is indeed only possible for rooted phones. 

So the only way to find the troubling bookmarks was within PinDroid. After a bit of playing I noted an interesting behavior: quickly scrolling down the bookmarks, the app would stall at bookmarks with long descriptions. For those, PinDroid also displayed an icon denoting a problem with syncing. Delete or edit them, and it syncing will work again. 

Note that PinDroid seems to tolerate a number troubling bookmarks, only after 5 or so it will stop syncing.
